name: manifold_hub
description: "Manifold hub for Windows"
publish_to: 'none'
version: 1.2.0+5

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  cryptography: ^2.9.0
  ffi: ^2.1.4
  win32: ^6.4.0
  media_kit: ^1.2.6
  media_kit_libs_windows_video: ^1.0.11
  flutter_svg: ^2.3.0
  window_manager: ^0.5.2
  tray_manager: ^0.5.3
  archive: ^4.3.0
  package_info_plus: ^10.2.2
  url_launcher: ^6.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/manifold.svg
    - assets/tray.ico
